config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

def index
  @tasks = Task.all
end

def show
@task = Task.find(params[:id])
end

def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def update
     @task = Task.find(params[:id])
    @task.update(update_task_params)
    redirect_to tasks_path
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :status)
  end

def update_task_params
    params.require(:task).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |t| %>

  <%= t.text_field :title %>
  <%= t.text_field :status %>
  <%= t.submit %>

<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<% @tasks.each_with_index do |task| %>
  <%= link_to task.title, task_path(task) %>
  <p><%= task.title %></p>
  <p><%= task.status %></p>
  <%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |t| %>

  <%= t.text_field :title %>
  <%= t.text_field :status %>
  <%= t.submit %>

<% end %>

app/views/tasks/show.html.erb
<h3> <%= @task.title %></h3>
<p><%= @task.status %></p>